openapi: "3.0.0"


info:
  title: SamGTU Navigation
  version: "1.0"


servers:
  - url: http://localhost:8080/


paths:
  /map/building/{id}:
    get:
      tags: [Map]
      operationId: getMapBuildingById
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        200:
          description: Operation went successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/map_building"
        404:
          description: Map building was not found
                
  /map/domain/{id}:
    get:
      tags: [Map]
      operationId: getMapDomainById
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        200:
          description: Operation went successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/map_domain"
        404:
          description: Map domain was not found
                
  /navigation:
    post:
      tags: [ Navigation ]
      operationId: findPath
      requestBody:
        content:
          application/json:
            schema:
              title: NavigationRequest
              type: object
              properties:
                startPoint:
                  $ref: "#/components/schemas/nav_point"
                endPoint:
                  $ref: "#/components/schemas/nav_point"
      responses:
        200:
          description: Operation went successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/nav_point"
        404:
          description: Unable to find path
      

components:
  schemas:
    bbox:
      title: BoundingBox
      type: object
      properties:
        positionX: { type: number }
        positionY: { type: number }
        width: { type: number }
        height: { type: number }
    map_object:
      title: MapObject
      properties:
        id: { type: integer }
        type: { type: string }
        number: { type: integer }
        displayName: { type: string }
        displayDescription: { type: string }
        bboxes:
          type: array
          items: { $ref: "#/components/schemas/bbox" }
    map_building:
      title: MapBuilding
      type: object
      properties:
        id: { type: integer }
        latitude: { type: number }
        longitude: { type: number }
        number: { type: integer,  }
        displayName: { type: string }
        displayDescription: { type: string }
        domainIds:
          type: array
          items: { type: integer }
    map_domain_image:
      title: DomainImage
      type: object
      properties:
        url: { type: string }
        realWidth: { type: number }
        realOffsetX: { type: number }
        realOffsetY: { type: number }
    map_domain:
      title: MapDomain
      type: object
      properties:
        id: { type: integer }
        mapBuildingId: { type: integer }
        number: { type: integer }
        image:
          $ref: "#/components/schemas/map_domain_image"
        mapObjects:
          type: array
          items:
            $ref: "#/components/schemas/map_object"
    nav_point:
      title: NavigationPoint
      type: object
      properties:
        positionX: { type: number }
        positionY: { type: number }
        domainId: { type: integer }


tags:
  - name: Map
  - name: Navigation
