openapi: "3.0.0"


info:
  title: SamGTU Navigation
  version: "1.0"


servers:
  - url: http://localhost:8080/


paths:
  /map/building/{id}:
    get:
      tags: [Map]
      operationId: getMapBuildingById
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        200:
          description: Operation went successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: { type: integer }
                  latitude: { type: number }
                  longitude: { type: number }
                  number: { type: integer,  }
                  display_name: { type: string }
                  display_description: { type: string }
                  domain_id:
                    type: array
                    items: { type: integer }
  /map/domain/{id}:
    get:
      tags: [Map]
      operationId: getMapDomainById
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        200:
          description: Operation went successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: { type: integer }
                  map_building_id: { type: integer }
                  number: { type: integer }
                  image:
                    type: object
                    properties:
                      url: { type: string }
                      real_width: { type: number }
                      real_offset_x: { type: number }
                      real_offset_y: { type: number }
                  map_objects:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: integer }
                        type: { type: string }
                        number: { type: integer }
                        display_name: { type: string }
                        display_description: { type: string }
                        bboxes:
                          type: array
                          items:
                            type: object
                            properties:
                              position_x: { type: number }
                              position_y: { type: number }
                              width: { type: number }
                              height: { type: number }
                              
  /navigation:
    post:
      tags: [ Navigation ]
      operationId: findPath
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                start_point:
                  type: object
                  properties:
                    x: { type: number }
                    y: { type: number }
                    domain_id: { type: integer }
                end_point:
                  type: object
                  properties:
                    x: { type: number }
                    y: { type: number }
                    domain_id: { type: integer }
      responses:
        200:
          description: Operation went successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    x: { type: number }
                    y: { type: number }
                    domain_id: { type: integer }
                    building_id: { type: integer }


tags:
  - name: Map
  - name: Navigation
