openapi: "3.0.0"


info:
  title: SamGTU Navigation
  version: "1.0"


servers:
  - url: http://localhost:8080/


paths:
  /map/building/{id}:
    get:
      tags: [Map]
      operationId: getMapBuildingById
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        200:
          description: Operation went successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/map_building"
                
  /map/domain/{id}:
    get:
      tags: [Map]
      operationId: getMapDomainById
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        200:
          description: Operation went successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/map_domain"
                
  /navigation:
    post:
      tags: [ Navigation ]
      operationId: findPath
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                start_point:
                  $ref: "#/components/schemas/nav_point"
                end_point:
                  $ref: "#/components/schemas/nav_point"
      responses:
        200:
          description: Operation went successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/nav_point"
      

components:
  schemas:
    bbox:
      title: BoundingBox
      type: object
      properties:
        pos_x: { type: number }
        pos_y: { type: number }
        width: { type: number }
        height: { type: number }
    map_object:
      title: MapObject
      properties:
        id: { type: integer }
        type: { type: string }
        number: { type: integer }
        display_name: { type: string }
        display_description: { type: string }
        bboxes:
          type: array
          items: { $ref: "#/components/schemas/bbox" }
    map_building:
      title: MapBuilding
      type: object
      properties:
        id: { type: integer }
        latitude: { type: number }
        longitude: { type: number }
        number: { type: integer,  }
        display_name: { type: string }
        display_description: { type: string }
        domain_ids:
          type: array
          items: { type: integer }
    map_domain_image:
      title: MapDomainImage
      type: object
      properties:
        url: { type: string }
        real_width: { type: number }
        real_offset_x: { type: number }
        real_offset_y: { type: number }
    map_domain:
      title: MapDomain
      type: object
      properties:
        id: { type: integer }
        map_building_id: { type: integer }
        number: { type: integer }
        image:
          $ref: "#/components/schemas/map_domain_image"
        map_objects:
          type: array
          items:
            $ref: "#/components/schemas/map_object"
    nav_point:
      title: NavigationPoint
      type: object
      properties:
        pos_x: { type: number }
        pos_y: { type: number }
        domain_id: { type: integer }


tags:
  - name: Map
  - name: Navigation
