version: "2.13.0"


services:
  backend:
    build:
      context: backend
      args:
        BACKEND_PORT: $BACKEND_PORT
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
    secrets:
      - source: backend-db-url
        target: database_url
      # - source: backend-secret-key
      #   target: secret_key
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER_FILE: "/run/secrets/postgres-username"
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres-password"
    secrets:
      - postgres-username
      - postgres-password
  
  frontend:
    build:
      context: frontend
      target: prod
      args:
        FRONTEND_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - backend


secrets:
  postgres-username:
    environment: POSTGRES_USERNAME
  postgres-password:
    environment: POSTGRES_PASSWORD

  backend-db-url:
    environment: BACKEND_DB_URL
  # backend-secret-key:
  #   environment: BACKEND_SECRET_KEY


volumes:
  postgres-data:
