version: "2.13.0"


services:
  backend:
    build:
      context: backend
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    secrets:
      - source: postgres-user
        target: spring.datasource.username
      - source: postgres-password
        target: spring.datasource.password
      - source: spring.datasource.url
    environment:
      SERVER_PORT: $SERVER_PORT
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15-alpine
    healthcheck:
      test: pg_isready -U $POSTGRES_USERNAME -d $POSTGRES_DB
      interval: 3s
      retries: 15
      start_period: 5s
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER_FILE: "/run/secrets/postgres-user"
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres-password"
    secrets:
      - postgres-user
      - postgres-password
  
  frontend:
    build:
      context: frontend
      target: prod
      args:
        FRONTEND_PORT: $FRONTEND_PORT
        BACKEND_URL: http://backend:$SERVER_PORT
    ports:
      - "$FRONTEND_PORT:$FRONTEND_PORT"
    depends_on:
      - backend


secrets:
  postgres-user:
    environment: POSTGRES_USERNAME
  postgres-password:
    environment: POSTGRES_PASSWORD
  spring.datasource.url:
    environment: SPRING_DATASOURCE_URL


volumes:
  postgres-data:
