
name: Deploy frontend on Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Check out the repo
       uses: actions/checkout@v3
     
     - name: Setup Node.js environment
       uses: actions/setup-node@v2
     
     - name: Install dependencies
       run: cd frontend && npm install
      
     - name: Create .env file
       run: echo {{ $secrets.PAGES_DOTENV_FILE }} > ./frontend/.env
     
     - name: Build project
       run: cd frontend && npm run build --base=https://adeda-team-inc.github.io/SamGTU-navigation/
        
     - name: Upload GitHub Pages artifact
       uses: actions/upload-pages-artifact@v1
       with:
         path: ./frontend/dist
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
